services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agendamento_api
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"